// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext {
        version = [
                "kotlin": "1.4.10",
                "coroutine": "1.4.2",
                "retrofit": "2.7.1",
                "room": "2.2.6",
                "androidx": "2.3.0",
                "navigation": "2.3.3",
                "work": "2.5.0",
                "security": "1.1.0-alpha03",
                "timber": "4.7.1",
                "koin": "2.1.2",
                "biweekly": "0.6.5",
                "constraint_layout": "2.0.1",
                "viewpager2": "1.1.0-alpha01",
                "material": "1.3.0",
                "androidx_test": "1.3.0",
                "serialization": "1.0.1",
                "assisted_inject" : "0.6.0",
                "hilt_android": "2.29.1-alpha",
                "hilt_androidx": "1.0.0-alpha03",

                "proton_core_crypto": "1.0.1",
                "proton_core_account": "1.0.1",
                "proton_core_account_manager": "1.0.2",
                "proton_core_account_manager_dagger": "1.0.2",
                "proton_core_auth": "1.0",
                "proton_core_user": "1.0.1",
                "proton_core_key": "1.0.1",
                "proton_core_human_verification": "0.2.5",
                "proton_core_data": "1.0",
                "proton_core_domain": "1.0",
                "proton_core_presentation": "0.5.7",
                "proton_core_networking": "1.0",
                "proton_core_util_kotlin": "0.2.4"
        ]
    }

    repositories {
        google()
        mavenCentral()
        maven { url "https://plugins.gradle.org/m2/" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${rootProject.ext.version.kotlin}"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:${rootProject.ext.version.navigation}"
        classpath "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.14.2"
        classpath "com.google.dagger:hilt-android-gradle-plugin:${rootProject.ext.version.hilt_android}"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        maven { url "https://plugins.gradle.org/m2/" }
        maven { url = "https://dl.bintray.com/proton/Core-publishing" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
