plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'maven-publish'
}

group = 'com.github.thellmund.Android-Week-View'
version = '5.3.0'

android {
    compileSdkVersion 32
    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 32
        multiDexEnabled true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
        coreLibraryDesugaringEnabled true
    }
}

dependencies {
    implementation project(':week-view-core')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.21"
    implementation "androidx.appcompat:appcompat:1.4.1"

    coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:1.1.5"

    testImplementation "junit:junit:4.13.2"
    testImplementation "org.mockito:mockito-core:4.5.1"
    testImplementation "org.mockito:mockito-inline:4.5.1"
}
