plugins {
//    id 'org.jetbrains.kotlin.multiplatform' version '1.4.10'
    id 'org.jetbrains.kotlin.plugin.serialization' version "1.7.20"
    id "org.sonarqube" version "3.3"
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'androidx.navigation.safeargs.kotlin'
apply plugin: 'io.gitlab.arturbosch.detekt'
apply plugin: 'dagger.hilt.android.plugin'
apply plugin: 'jacoco'

def sentryDsn = System.getenv("SENTRY_DSN_NEW") ?: ""
def storeFilePath = project.hasProperty('keyStoreFilePath') ? keyStoreFilePath : "protonkey.jks"
def storeKeyAlias = System.getenv("KEY_STORE_KEY_ALIAS") ?: 'proton'
def storePass = System.getenv("KEY_STORE_PASSWORD") ?: "\"Store password\""
def storeKeyPass = System.getenv("KEY_STORE_KEY_PASSWORD") ?: "\"Store key password\""

sonarqube {
    properties {
        property "sonar.projectKey", "android_calendar_proton-calendar-android_AYGvp8U7f_vcScryKn5V"
        property "sonar.qualitygate.wait", true
    }
}

detekt {
    config = files("$projectDir/config/detekt/detekt.yml")
}
tasks.named("detekt").configure {
    jvmTarget = "1.8"
    reports {
        xml.required.set(false)
        html.required.set(true)
        txt.required.set(false)
        custom {
            reportId = "DetektQualityOutputReport"
            destination = file("build/reports/detekt.json")
        }
    }
}

jacoco {
    toolVersion = '0.8.7'
}

tasks.withType(Test) {
    jacoco.includeNoLocationClasses = true
}

task jacocoTestReport(type: JacocoReport, dependsOn: ['testDebugUnitTest','createDebugCoverageReport']) {

    reports {
        xml.enabled = true
        html.enabled = true
    }

    def fileFilter = ['**/R.class', '**/R$*.class', '**/BuildConfig.*', '**/Manifest*.*', '**/*Test*.*', 'android/**/*.*', 'ch.protonmail.android.utils.nativelib', '**/ch/protonmail/**']
    def debugTree = fileTree(dir: "$project.buildDir/tmp/kotlin-classes/debug", excludes: fileFilter)
    def mainSrc = "${project.projectDir}/src/main/java"

    sourceDirectories.setFrom files([mainSrc])
    classDirectories.setFrom files([debugTree])
    executionData.setFrom fileTree(dir: "$buildDir", includes: [
            "**/*.exec",
            "**/*.ec"
    ])
}

task coverageReport() {
    dependsOn jacocoTestReport

    def reportFile = project.file("build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml")
    inputs.file(reportFile)

    doLast {
        def slurper = new XmlSlurper()
        slurper.setFeature("http://apache.org/xml/features/disallow-doctype-decl", false)
        slurper.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false)
        def xml = slurper.parse(reportFile)
        def counter = xml.counter.find {
            node -> node.@type == 'INSTRUCTION'
        }
        def missed = counter.@missed.toDouble()
        def covered = counter.@covered.toDouble()
        def total = missed + covered
        def percentage = covered / total * 100

        printf "Missed %.0f branches%n", missed
        printf "Covered %.0f branches%n", covered
        printf "Total %.0f%%%n", percentage
    }
}

tasks.withType(Test) {
    jacoco.includeNoLocationClasses = true
    jacoco.excludes = ['jdk.internal.*']
}

android {
    
    namespace 'me.proton.android.calendar'

    compileSdkVersion 33
    buildToolsVersion "30.0.3"
    ndkVersion "21.3.6528147"

    defaultConfig {
        applicationId "me.proton.android.calendar"
        minSdkVersion 23
        targetSdkVersion 33
        versionCode 183
        versionName "2.6.3"
        archivesBaseName = "ProtonCalendar-" + versionName + "(" + versionCode + ")"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        resConfigs 'en', 'ca', 'es-rES', 'es-rMX', 'fr', 'fr-rCA', 'pl', 'pt-rPT', 'ro', 'de', 'it', 'nl', 'uk'

        javaCompileOptions {
            annotationProcessorOptions {
                arguments += ["room.schemaLocation":"$projectDir/schemas".toString()]
            }
        }
    }

    signingConfigs {
//        debug { TODO
//            storeFile file('/Users/path-to-keystore')
//            storePassword '123456'
//            keyAlias 'debug-key'
//            keyPassword '123456'
//        }
        release {
            storeFile file(storeFilePath)
            storePassword storePass
            keyAlias storeKeyAlias
            keyPassword storeKeyPass
        }
    }

    buildTypes {
        release {
            minifyEnabled false // TODO turn off for initial beta release
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release

            buildConfigField("String", "SENTRY_DSN_NEW", "\"${sentryDsn}\"")
//            resValue("string", "build_time", "${minutesSinceEpoch}")
        }
        debug {
            buildConfigField("String", "SENTRY_DSN_NEW", "\"null\"")
            testCoverageEnabled true
        }
    }
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    testOptions {
        unitTests.all {
            useJUnitPlatform()
        }
    }
    kotlinOptions {
        jvmTarget = '11'
    }
    dataBinding {
        enabled = true
    }
    sourceSets {
        androidTest {
            java.srcDirs += "src/sharedTest/java"
        }
        test {
            java.srcDirs += "src/sharedTest/java"
        }
    }

}

kapt {
    correctErrorTypes true
}

tasks.register("getArchivesName"){
    doLast {
        println archivesBaseName
    }
}

tasks.withType(Test) {
    testLogging {
        events "passed", "skipped", "failed"
    }
}

dependencies {

    implementation project(path: ':week-view-core')
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'

    implementation(files("../../proton-libs/gopenpgp/gopenpgp.aar"))

    // Proton Core libraries.
    implementation "me.proton.core:account:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:account-manager:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:account-manager-dagger:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:auth:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:contact:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:country:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:crypto:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:crypto-validator:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:data:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:data-room:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:domain:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:event-manager:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:feature-flag:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:human-verification:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:key:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:mail-message:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:mail-settings:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:network:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:observability:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:payment:${rootProject.ext.version.proton_core}"
    // implementation "me.proton.core:payment-iap:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:plan:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:presentation:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:user:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:user-settings:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:util-android-dagger:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:util-kotlin:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:challenge:${rootProject.ext.version.proton_core}"
    implementation "me.proton.core:challenge-presentation:${rootProject.ext.version.proton_core}"

    implementation "androidx.activity:activity-ktx:1.5.1"

    // Assisted Inject.
    compileOnly "com.squareup.inject:assisted-inject-annotations-dagger2:${rootProject.ext.version.assisted_inject}"
    kapt "com.squareup.inject:assisted-inject-processor-dagger2:${rootProject.ext.version.assisted_inject}"

    // Hilt AndroidX (JetPack Integration).
//    implementation "androidx.hilt:hilt-lifecycle-viewmodel:${rootProject.ext.version.hilt_androidx}"
    implementation "androidx.hilt:hilt-work:${rootProject.ext.version.hilt_androidx}"
    kapt "androidx.hilt:hilt-compiler:${rootProject.ext.version.hilt_androidx}"

    // Hilt Android.
    implementation "com.google.dagger:hilt-android:${rootProject.ext.version.hilt_android}"
    kapt "com.google.dagger:hilt-android-compiler:${rootProject.ext.version.hilt_android}"

    implementation 'androidx.core:core-ktx:1.3.2'
    implementation "androidx.core:core-splashscreen:${rootProject.ext.version.splashscreen}"

    // Alpha version needed for custom language selection. This should be replaced as soon as a stable version is available
    implementation 'androidx.appcompat:appcompat:1.6.0-alpha05'
//    implementation 'androidx.appcompat:appcompat:1.1.0'
//    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation "com.google.android.material:material:${rootProject.ext.version.material}"
    implementation "androidx.constraintlayout:constraintlayout:${rootProject.ext.version.constraint_layout}"
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
    implementation "androidx.coordinatorlayout:coordinatorlayout:1.1.0"
    implementation "androidx.viewpager2:viewpager2:${rootProject.ext.version.viewpager2}"
//    implementation 'androidx.navigation:navigation-fragment:2.2.1'
//    implementation 'androidx.navigation:navigation-ui:2.2.1'
    implementation "androidx.navigation:navigation-fragment-ktx:${rootProject.ext.version.navigation}"
    implementation "androidx.navigation:navigation-ui-ktx:${rootProject.ext.version.navigation}"

    implementation "androidx.lifecycle:lifecycle-livedata-ktx:${rootProject.ext.version.androidx}"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:${rootProject.ext.version.androidx}"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:${rootProject.ext.version.androidx}"
//    For LifecycleScope, use androidx.lifecycle:lifecycle-runtime-ktx:2.2.0-alpha01 or higher.
//    For liveData, use androidx.lifecycle:lifecycle-livedata-ktx:2.2.0-alpha01 or higher.
    //noinspection GradleDependency
    implementation "androidx.work:work-runtime-ktx:${rootProject.ext.version.work}"

//    implementation "androidx.room:room-coroutines:2.2.4"
    implementation "androidx.room:room-runtime:${rootProject.ext.version.room}"
    kapt "androidx.room:room-compiler:${rootProject.ext.version.room}"
    implementation "androidx.room:room-ktx:${rootProject.ext.version.room}"

    implementation "io.insert-koin:koin-android:${rootProject.ext.version.koin}"
    implementation "io.insert-koin:koin-android-viewmodel:${rootProject.ext.version.koin}"

    implementation("com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:0.8.0")
    implementation "com.squareup.retrofit2:retrofit:${rootProject.ext.version.retrofit}"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:${rootProject.ext.version.coroutine}"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:${rootProject.ext.version.coroutine}"
    implementation "com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:0.9.2"
    implementation 'com.squareup.okhttp3:logging-interceptor:4.8.0'

    implementation "com.jakewharton.timber:timber:${rootProject.ext.version.timber}"

    implementation "com.googlecode.ez-vcard:ez-vcard:0.11.2"

    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:${rootProject.ext.version.serialization}"
//    implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime:${rootProject.ext.version.serialization}"


//    implementation "com.google.dagger:dagger-android:${rootProject.ext.dagger_version}"
//    kapt "com.google.dagger:dagger-compiler:${rootProject.ext.dagger_version}"
//    kapt "com.google.dagger:dagger-android-processor:${rootProject.ext.dagger_version}"

    implementation "androidx.security:security-crypto:${rootProject.ext.version.security}"
    implementation "com.google.crypto.tink:tink-android:1.5.0" // it's included in security-crypto

    implementation 'io.sentry:sentry-android:5.6.2'

    implementation "at.favre.lib:bcrypt:0.9.0"
//    implementation "org.mnode.ical4j:ical4j:${rootProject.ext.version.ical}"
    implementation "net.sf.biweekly:biweekly:${rootProject.ext.version.biweekly}"

    // Shared preferences
    implementation 'androidx.preference:preference-ktx:1.1.1'

    detekt 'io.gitlab.arturbosch.detekt:detekt-formatting:1.9.1'
    detekt 'io.gitlab.arturbosch.detekt:detekt-cli:1.9.1'
    detektPlugins 'io.gitlab.arturbosch.detekt:detekt-formatting:1.9.1'

    androidTestImplementation "io.mockk:mockk-android:1.13.3"
    androidTestImplementation "androidx.test:core:${rootProject.ext.version.androidx_test}"
    androidTestImplementation "androidx.test:runner:${rootProject.ext.version.androidx_test}"
    androidTestImplementation "androidx.test:rules:${rootProject.ext.version.androidx_test}"
    androidTestImplementation "androidx.test.ext:junit:1.1.2"
//    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

    testImplementation 'com.willowtreeapps.assertk:assertk-jvm:0.21'
    testImplementation "io.mockk:mockk:1.13.3"
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.5.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.5.0'

    testImplementation "io.insert-koin:koin-test:${rootProject.ext.version.koin}"

    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.9.1'

    // Core library
    testImplementation "androidx.arch.core:core-testing:2.1.0"
    androidTestImplementation "androidx.arch.core:core-testing:2.1.0"

    implementation 'com.google.android.gms:play-services-auth:20.2.0'
}
