plugins {
//    id 'org.jetbrains.kotlin.multiplatform' version '1.4.10'
    id 'org.jetbrains.kotlin.plugin.serialization' version "1.4.10"
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'androidx.navigation.safeargs.kotlin'
apply plugin: 'io.gitlab.arturbosch.detekt'
apply plugin: 'dagger.hilt.android.plugin'

def sentryDsn = project.hasProperty("sentryDsn") ? sentryDsn : "https://abc@sentry.com/666"
def storeFilePath = project.hasProperty('keyStoreFilePath') ? keyStoreFilePath : "protonkey.jks"
def storeKeyAlias = project.hasProperty('keyStoreKeyAlias') ? keyStoreKeyAlias : 'proton'
def storePass = project.hasProperty('keyStorePassword') ? keyStorePassword : "\"Store password\""
def storeKeyPass = project.hasProperty('keyStoreKeyPassword') ? keyStoreKeyPassword : "\"Store key password\""

detekt {
    failFast = false
    config = files("$projectDir/config/detekt/detekt.yml")
    reports {
        xml {
            enabled = false
        }
        html {
            enabled = true
        }
        txt {
            enabled = false
        }
        custom {
            reportId = "DetektQualityOutputReport"
            destination = file("build/reports/detekt.json")
        }
    }
}

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.2"
    ndkVersion "21.3.6528147"
    
    defaultConfig {
        applicationId "me.proton.android.calendar"
        minSdkVersion 23
        targetSdkVersion 30
        versionCode 48
        versionName "0.17.10"
        archivesBaseName = "ProtonCalendar-" + versionName + "(" + versionCode + ")"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
//        debug { TODO
//            storeFile file('/Users/path-to-keystore')
//            storePassword '123456'
//            keyAlias 'debug-key'
//            keyPassword '123456'
//        }
        release {
            storeFile file(storeFilePath)
            storePassword storePass
            keyAlias storeKeyAlias
            keyPassword storeKeyPass
        }
    }

    buildTypes {
        release {
            minifyEnabled false // TODO turn off for initial beta release
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release

            buildConfigField("String", "SENTRY_DSN", "\"${sentryDsn}\"")
//            resValue("string", "build_time", "${minutesSinceEpoch}")
        }
        debug {
            buildConfigField("String", "SENTRY_DSN", "\"null\"")
        }
    }
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    testOptions {
        unitTests.all {
            useJUnitPlatform()
        }
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    dataBinding {
        enabled = true
    }
}

kapt {
    correctErrorTypes true
}

tasks.withType(Test) {
    testLogging {
        events "passed", "skipped", "failed"
    }
}

dependencies {

    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.1'

    implementation fileTree(dir: "libs", include: ["*.jar", "*.aar"])

    // Proton Core libraries.
    implementation "me.proton.core:account:${rootProject.ext.version.proton_core_account}"
    implementation "me.proton.core:account-manager:${rootProject.ext.version.proton_core_account_manager}"
    implementation "me.proton.core:account-manager-dagger:${rootProject.ext.version.proton_core_account_manager_dagger}"
    implementation "me.proton.core:auth:${rootProject.ext.version.proton_core_auth}"
    implementation "me.proton.core:human-verification:${rootProject.ext.version.proton_core_human_verification}"
    implementation "me.proton.core:data:${rootProject.ext.version.proton_core_data}"
    implementation "me.proton.core:domain:${rootProject.ext.version.proton_core_domain}"
    implementation "me.proton.core:presentation:${rootProject.ext.version.proton_core_presentation}"
    implementation "me.proton.core:network:${rootProject.ext.version.proton_core_networking}"
    implementation "me.proton.core:util-kotlin:${rootProject.ext.version.proton_core_util_kotlin}"

    implementation "androidx.activity:activity-ktx:1.2.0-rc01"

    // Assisted Inject.
    compileOnly "com.squareup.inject:assisted-inject-annotations-dagger2:${rootProject.ext.version.assisted_inject}"
    kapt "com.squareup.inject:assisted-inject-processor-dagger2:${rootProject.ext.version.assisted_inject}"

    // Hilt AndroidX (JetPack Integration).
    implementation "androidx.hilt:hilt-lifecycle-viewmodel:${rootProject.ext.version.hilt_androidx}"
    implementation "androidx.hilt:hilt-work:${rootProject.ext.version.hilt_androidx}"
    kapt "androidx.hilt:hilt-compiler:${rootProject.ext.version.hilt_androidx}"

    // Hilt Android.
    implementation "com.google.dagger:hilt-android:${rootProject.ext.version.hilt_android}"
    kapt "com.google.dagger:hilt-android-compiler:${rootProject.ext.version.hilt_android}"

    implementation "org.jetbrains.kotlin:kotlin-stdlib:${rootProject.ext.version.kotlin}"
    implementation 'androidx.core:core-ktx:1.3.2'
//    implementation 'androidx.appcompat:appcompat:1.1.0'
//    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation "com.google.android.material:material:${rootProject.ext.version.material}"
    implementation "androidx.constraintlayout:constraintlayout:${rootProject.ext.version.constraint_layout}"
    implementation "androidx.coordinatorlayout:coordinatorlayout:1.1.0"
    implementation "androidx.viewpager2:viewpager2:${rootProject.ext.version.viewpager2}"
//    implementation 'androidx.navigation:navigation-fragment:2.2.1'
//    implementation 'androidx.navigation:navigation-ui:2.2.1'
    implementation "androidx.navigation:navigation-fragment-ktx:${rootProject.ext.version.navigation}"
    implementation "androidx.navigation:navigation-ui-ktx:${rootProject.ext.version.navigation}"

    implementation "androidx.lifecycle:lifecycle-extensions:${rootProject.ext.version.androidx}"
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:${rootProject.ext.version.androidx}"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:${rootProject.ext.version.androidx}"
//    For LifecycleScope, use androidx.lifecycle:lifecycle-runtime-ktx:2.2.0-alpha01 or higher.
//    For liveData, use androidx.lifecycle:lifecycle-livedata-ktx:2.2.0-alpha01 or higher.
    //noinspection GradleDependency
    implementation "androidx.work:work-runtime-ktx:${rootProject.ext.version.work}"

//    implementation "androidx.room:room-coroutines:2.2.4"
    implementation "androidx.room:room-runtime:${rootProject.ext.version.room}"
    kapt "androidx.room:room-compiler:${rootProject.ext.version.room}"
    implementation "androidx.room:room-ktx:${rootProject.ext.version.room}"

    implementation "org.koin:koin-android:${rootProject.ext.version.koin}"
    implementation "org.koin:koin-android-viewmodel:${rootProject.ext.version.koin}"

    implementation("com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:0.8.0")
    implementation "com.squareup.retrofit2:retrofit:${rootProject.ext.version.retrofit}"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:${rootProject.ext.version.coroutine}"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:${rootProject.ext.version.coroutine}"
    implementation "com.jakewharton.retrofit:retrofit2-kotlin-coroutines-adapter:0.9.2"
    implementation 'com.squareup.okhttp3:logging-interceptor:4.8.0'

    implementation "com.jakewharton.timber:timber:${rootProject.ext.version.timber}"

    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:${rootProject.ext.version.serialization}"
//    implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime:${rootProject.ext.version.serialization}"


//    implementation "com.google.dagger:dagger-android:${rootProject.ext.dagger_version}"
//    kapt "com.google.dagger:dagger-compiler:${rootProject.ext.dagger_version}"
//    kapt "com.google.dagger:dagger-android-processor:${rootProject.ext.dagger_version}"

    implementation "androidx.security:security-crypto:${rootProject.ext.version.security}"
    implementation "com.google.crypto.tink:tink-android:1.4.0" // it's included in security-crypto

    implementation 'io.sentry:sentry-android:1.7.30'

    implementation "at.favre.lib:bcrypt:0.9.0"
//    implementation "org.mnode.ical4j:ical4j:${rootProject.ext.version.ical}"
    implementation "net.sf.biweekly:biweekly:${rootProject.ext.version.biweekly}"

    detekt 'io.gitlab.arturbosch.detekt:detekt-formatting:1.9.1'
    detekt 'io.gitlab.arturbosch.detekt:detekt-cli:1.9.1'
    detektPlugins 'pm.algirdas.detekt:codeanalysis:0.3.3'
    detektPlugins 'io.gitlab.arturbosch.detekt:detekt-formatting:1.9.1'

    androidTestImplementation "androidx.test:core:${rootProject.ext.version.androidx_test}"
    androidTestImplementation "androidx.test:runner:${rootProject.ext.version.androidx_test}"
    androidTestImplementation "androidx.test:rules:${rootProject.ext.version.androidx_test}"
    androidTestImplementation "androidx.test.ext:junit:1.1.2"
//    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

    testImplementation 'com.willowtreeapps.assertk:assertk-jvm:0.21'
    testImplementation "io.mockk:mockk:1.9.3" // TODO downgrade to 1.9.2 in case of problems with tests
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.5.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.5.0'

    testImplementation "org.koin:koin-test:${rootProject.ext.version.koin}"

}
