package me.proton.android.calendar.common

import android.content.Context
import android.content.SharedPreferences
import androidx.security.crypto.EncryptedSharedPreferences
import androidx.security.crypto.MasterKey
import me.proton.android.calendar.domain.ValueStore
import me.proton.android.calendar.domain.ValueStoreProvider


class ValueStoreProviderImpl(private val sharedPreferencesProvider: SharedPreferencesProvider) : ValueStoreProvider {

    private val valueStores = mutableMapOf<String, ValueStore>()

    inner class ValueStoreImpl(private val sharedPreferences: SharedPreferences) : ValueStore {
        @Synchronized
        override fun putString(key: String, value: String) = sharedPreferences.edit().putString(
            key,
            value
        ).apply()
        @Synchronized
        override fun getString(key: String): String? = sharedPreferences.getString(key, null)
        @Synchronized
        override fun putStringInSet(setName: String, key: String, value: String) = sharedPreferences.edit().putString(
            "$setName~$key",
            value
        ).apply()
        @Synchronized
        override fun getStringFromSet(setName: String, key: String): String? = sharedPreferences.getString(
            "$setName~$key",
            null
        )
    }

    @Synchronized
    override fun provideValueStore(userId: String): ValueStore {
        return valueStores.getOrPut(userId) {
            ValueStoreImpl(sharedPreferencesProvider.provideSharedPreferencesFor(userId))
        }
    }

}

// TODO instrumented test
class SharedPreferencesProvider(private val applicationContext: Context) {

    private val encryptedSharedPreferences = mutableMapOf<String, SharedPreferences>()

    // MasterKey for EncryptedSharedPreferences, generated by androidx library
    private val masterKey by lazy {
        MasterKey.Builder(applicationContext)
            .setKeyScheme(MasterKey.KeyScheme.AES256_GCM)
            .build()
    }

    // TODO if this goes wrong, all bets are off -- handle this on application init
    @Throws(Exception::class)
    fun provideSharedPreferencesFor(userId: String) : SharedPreferences {
        return encryptedSharedPreferences.getOrPut(userId) {
            EncryptedSharedPreferences.create(
                applicationContext,
                userId,
                masterKey,
                EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,
                EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM
            )
        }
    }
}
